Repository Lazarus-org/django_logging, pull requests merged in 2024-10, with the labels that each got.

#91 ✨ 💥 Add CantextVariable Manager class
  .github/workflows/ci.yml
  .pre-commit-config-ci.yaml
  .pre-commit-config.yaml
  django_logging/contextvar/__init__.py
  django_logging/contextvar/contextvar_manager.py
  django_logging/filters/__init__.py
  django_logging/filters/context_filter.py
  django_logging/tests/fixtures/formatters.py
Labels: enhancement

#97 ✨ Add JSONFormatter for structured logging with key-value support
  django_logging/formatters/base.py
  django_logging/formatters/json_formatter.py
Labels: enhancement

#99 ✨ Add XMLFormatter for structured logging in XML format
  django_logging/formatters/xml_formatter.py
Labels: enhancement

#100 ⚡ 🔨 Update configs
  django_logging/constants/__init__.py
  django_logging/constants/ansi_colors.py
  django_logging/constants/config_types.py
  django_logging/constants/default_settings.py
  django_logging/constants/log_format_options.py
  django_logging/constants/log_format_specifiers.py
  django_logging/decorators/execution_tracking.py
  django_logging/settings/conf.py
  django_logging/utils/get_conf.py
  django_logging/utils/set_conf.py
  django_logging/utils/time.py
  django_logging/validators/config_validators.py
  django_logging/validators/email_settings_validator.py
Labels: enhancement, configuration

#101 ✨ feat(formatters): Add FLATFormatter to Format Log Records as Flat Line Key-Value Pairs
  django_logging/formatters/__init__.py
  django_logging/formatters/flat_formatter.py
Labels: enhancement

#102 Feat/middleware
  django_logging/middleware/base.py
  django_logging/middleware/request_middleware.py
Labels: enhancement

#103 Feat/pretty format
  django_logging/management/commands/generate_pretty_json.py
  django_logging/management/commands/generate_pretty_xml.py
Labels: enhancement

#104 Feat/monitor log size
  django_logging/management/commands/logs_size_audit.py
  django_logging/management/commands/send_logs.py
  django_logging/middleware/__init__.py
  django_logging/middleware/monitor_log_size.py
Labels: enhancement

#106 Feat/validators
  django_logging/formatters/__init__.py
  django_logging/formatters/base.py
  django_logging/formatters/flat_formatter.py
  django_logging/formatters/xml_formatter.py
  django_logging/middleware/monitor_log_size.py
  django_logging/settings/checks.py
  django_logging/validators/config_validators.py
Labels: enhancement, configuration

#109 Feat/tests
  django_logging/tests/commands/test_generate_pretty_json.py
  django_logging/tests/commands/test_generate_pretty_xml.py
  django_logging/tests/commands/test_logs_size_audit.py
  django_logging/tests/conftest.py
  django_logging/tests/contextvar/__init__.py
  django_logging/tests/contextvar/test_contextvar_manager.py
  django_logging/tests/decorators/test_execution_tracking.py
  django_logging/tests/fixtures/__init__.py
  django_logging/tests/fixtures/commands_fixture.py
  django_logging/tests/fixtures/conf_fixture.py
  django_logging/tests/fixtures/formatters.py
  django_logging/tests/fixtures/log_record_fixture.py
  django_logging/tests/fixtures/request_middleware_fixture.py
  django_logging/tests/fixtures/settings_fixture.py
  django_logging/tests/formatters/test_base_formatter.py
  django_logging/tests/formatters/test_flat_line_formatter.py
  django_logging/tests/formatters/test_json_formatter.py
  django_logging/tests/formatters/test_xml_formatter.py
  django_logging/tests/middleware/test_base_middleware.py
  django_logging/tests/middleware/test_monitor_log_size.py
  django_logging/tests/middleware/test_request_middleware.py
  django_logging/tests/settings/test_checks.py
  django_logging/tests/setup.py
  django_logging/tests/utils/test_context_manager.py
  django_logging/tests/utils/test_email_notifier.py
  django_logging/tests/utils/test_get_conf.py
  django_logging/tests/utils/test_log_and_notify.py
  django_logging/tests/utils/test_process_file.py
  django_logging/tests/utils/test_set_conf.py
  django_logging/tests/validators/test_config_validators.py
  django_logging/tests/validators/test_email_settings_validator.py
Labels: test

#110 Chore/pytest conf
  .github/workflows/ci.yml
  .pre-commit-config-ci.yaml
  .pre-commit-config.yaml
  django_logging/contextvar/contextvar_manager.py
  django_logging/templates/email_notifier_template.html
  django_logging/utils/console_colorizer.py
  django_logging/utils/log_email_notifier/notifier.py
  packages/requirements-dev.txt
  pyproject.toml
Labels: enhancement, configuration

#112 Update/docs
  .gitignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/conf.py
  docs/contributing.rst
  docs/index.rst
  docs/quick_start.rst
  docs/settings.rst
  docs/usage.rst
  poetry.lock
Labels: documentation

#114 Chore/support py3.13
  .github/workflows/ci.yml
  README.md
  django_logging/tests/constants.py
  docs/index.rst
  packages/requirements-dev.txt
  packages/requirements.txt
  poetry.lock
  pyproject.toml
  tox.ini
Labels: dependency, configuration

#116 Add LogiBoard interface
  django_logging/static/LogiBoard/css/app.css
  django_logging/static/LogiBoard/css/error_response.css
  django_logging/static/LogiBoard/imgs/Lazarus.jpeg
  django_logging/static/LogiBoard/imgs/close-50.png
  django_logging/static/LogiBoard/imgs/done-50.png
  django_logging/static/LogiBoard/imgs/exclamation-mark.png
  django_logging/static/LogiBoard/imgs/file-icon.png
  django_logging/static/LogiBoard/imgs/folder-icon.png
  django_logging/static/LogiBoard/imgs/json-icon.png
  django_logging/static/LogiBoard/imgs/multiply-50.png
  django_logging/static/LogiBoard/imgs/open-50.png
  django_logging/static/LogiBoard/imgs/pause-50.png
  django_logging/static/LogiBoard/imgs/search-icon.png
  django_logging/static/LogiBoard/imgs/stop-50.png
  django_logging/static/LogiBoard/imgs/txt-icon.png
  django_logging/static/LogiBoard/imgs/upload-to-cloud-50.png
  django_logging/static/LogiBoard/imgs/xml-icon.png
  django_logging/static/LogiBoard/js/scripts.js
  django_logging/templates/error_response.html
  django_logging/templates/log_iboard.html
Labels: enhancement

#118 Feat/log iboard view
  django_logging/constants/default_settings.py
  django_logging/settings/checks.py
  django_logging/tests/conftest.py
  django_logging/tests/fixtures/__init__.py
  django_logging/tests/fixtures/views_fixture.py
  django_logging/tests/setup.py
  django_logging/tests/views/__init__.py
  django_logging/tests/views/test_log_iboard.py
  django_logging/urls.py
  django_logging/utils/get_conf.py
  django_logging/views/__init__.py
  django_logging/views/log_iboard.py
  pyproject.toml
Labels: enhancement

#121 📚 Update README.md sections
  README.md
Labels: documentation

#122 ⚡ 🎨 🔨 ✨ Improve upload page and style
  django_logging/static/LogiBoard/css/app.css
  django_logging/static/LogiBoard/js/scripts.js
  django_logging/templates/log_iboard.html
Labels: enhancement

#125 ✨ 🔨 Feat/settings manager
  django_logging/constants/config_types.py
  django_logging/management/commands/generate_pretty_json.py
  django_logging/management/commands/generate_pretty_xml.py
  django_logging/management/commands/logs_size_audit.py
  django_logging/management/commands/send_logs.py
  django_logging/middleware/monitor_log_size.py
  django_logging/settings/__init__.py
  django_logging/settings/checks.py
  django_logging/settings/conf.py
  django_logging/settings/manager.py
  django_logging/tests/commands/test_generate_pretty_json.py
  django_logging/tests/commands/test_generate_pretty_xml.py
  django_logging/tests/commands/test_logs_size_audit.py
  django_logging/tests/commands/test_send_logs.py
  django_logging/tests/fixtures/settings_fixture.py
  django_logging/tests/fixtures/views_fixture.py
  django_logging/tests/settings/test_checks.py
  django_logging/tests/utils/test_get_conf.py
  django_logging/utils/get_conf.py
  django_logging/utils/set_conf.py
Labels: enhancement, test

#126 ⚡ 🎨 Update(utils) colors in console colorizer & add new placeholders
  django_logging/constants/log_format_options.py
  django_logging/constants/log_format_specifiers.py
  django_logging/utils/console_colorizer.py
Labels: enhancement
